name: learn-github-actions
on: [push, workflow_dispatch]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: master
      - run: bundle --version
      - name: Set bundler version
        run: bundle update --bundler
        working-directory: app
      - run: bundle --version
      - name: Install dependencies
        run: bundle install
        working-directory: app
      - run: ./app/bin/data_fetcher
